[2025-07-30T21:31:43.953+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_medallon.crea_vista_analitica manual__2025-07-30T21:31:25+00:00 [queued]>
[2025-07-30T21:31:44.045+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_medallon.crea_vista_analitica manual__2025-07-30T21:31:25+00:00 [queued]>
[2025-07-30T21:31:44.046+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-30T21:31:44.090+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): crea_vista_analitica> on 2025-07-30 21:31:25+00:00
[2025-07-30T21:31:44.096+0000] {standard_task_runner.py:60} INFO - Started process 104 to run task
[2025-07-30T21:31:44.101+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_medallon', 'crea_vista_analitica', 'manual__2025-07-30T21:31:25+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_medallon_dag.py', '--cfg-path', '/tmp/tmp4c465nmb']
[2025-07-30T21:31:44.104+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask crea_vista_analitica
[2025-07-30T21:31:44.202+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_medallon.crea_vista_analitica manual__2025-07-30T21:31:25+00:00 [running]> on host 70eaa744a05c
[2025-07-30T21:31:44.344+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateo.biasotto' AIRFLOW_CTX_DAG_ID='pipeline_medallon' AIRFLOW_CTX_TASK_ID='crea_vista_analitica' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T21:31:25+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T21:31:25+00:00'
[2025-07-30T21:31:44.345+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-30T21:31:44.346+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/04_crea_vista_analitica.py']
[2025-07-30T21:31:44.354+0000] {subprocess.py:86} INFO - Output:
[2025-07-30T21:31:44.469+0000] {subprocess.py:93} INFO - üîó Conectado a PostgreSQL en postgres:5432/medallon_db
[2025-07-30T21:31:44.469+0000] {subprocess.py:93} INFO - ‚ñ∂Ô∏è Ejecutando: /opt/airflow/sql/04_vista_analisis.sql
[2025-07-30T21:31:44.470+0000] {subprocess.py:93} INFO - ‚ö†Ô∏è Error ejecutando el script de la vista:
[2025-07-30T21:31:44.470+0000] {subprocess.py:93} INFO - column f.taligent_id does not exist
[2025-07-30T21:31:44.471+0000] {subprocess.py:93} INFO - LINE 3:     f.taligent_id,
[2025-07-30T21:31:44.472+0000] {subprocess.py:93} INFO -             ^
[2025-07-30T21:31:44.472+0000] {subprocess.py:93} INFO - 
[2025-07-30T21:31:44.479+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-30T21:31:44.531+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=pipeline_medallon, task_id=crea_vista_analitica, execution_date=20250730T213125, start_date=20250730T213143, end_date=20250730T213144
[2025-07-30T21:31:44.596+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-30T21:31:44.641+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
